name: PaperPanel
version: '2.6.5'
main: de.kaicraft.adminpanel.ServerAdminPanelPlugin
api-version: '2.6.5'
author: AerohDEV
description: Web-based admin panel for Minecraft Paper servers
website: https://github.com/aerohdev/Minecraft-Admin-WebApp

commands:
  paperpanel:
    description: PaperPanel commands
    usage: /paperpanel [reload|status|resetpassword]
    aliases: [pp, panel]
    permission: paperpanel.use

permissions:
  paperpanel.use:
    description: Allows use of PaperPanel
    default: op
  paperpanel.webaccess:
    description: Allows access to the web panel
    default: op
